#!/bin/bash
# this file will be overwritten by the project setup script
SIMICS_BASE_PACKAGE="/home/rijegaro/Documents/intel-simics-package-manager-1.7.2/simics-6.0.166"
export SIMICS_BASE_PACKAGE
if [ -f "/home/rijegaro/Documents/simics-projects/academia-collaboration/simics-project/.package-list" ]; then
    exec "/home/rijegaro/Documents/intel-simics-package-manager-1.7.2/simics-6.0.166/bin/simics-eclipse" --package-list "/home/rijegaro/Documents/simics-projects/academia-collaboration/simics-project/.package-list" --project "/home/rijegaro/Documents/simics-projects/academia-collaboration/simics-project" "$@"
else
    exec "/home/rijegaro/Documents/intel-simics-package-manager-1.7.2/simics-6.0.166/bin/simics-eclipse" --project "/home/rijegaro/Documents/simics-projects/academia-collaboration/simics-project" "$@"
fi
